### ISSUE TITLE
Cannot create a new user

### ISSUE THREAD

**Issue by Phlow2001** [psiho/jsbench-me#10]
error! InvalidParameterException

I have tried different emails, different passwords, same error.

**Comment by psiho** [comment]
Can you please tell me more about what you tried. Maybe what browser you're using? username? It seems I haven't tested IE properly but I cannot reproduce your error on Chrome and there are already quite a few registered users so it seems they haven't had that problem either.

**Comment by Phlow2001** [comment]
I just tried again. It appears to be the result of having a space in my username.  I was able to create a user with no spaces, and the same email/password I was trying originally.

**Comment by psiho** [comment]
Anyway, I'll still mark this as a bug. It shouldn't pass local validation. Thanks for noticing!

**Comment by psiho** [comment]
This small fix was published together with MS browsers support in latest v0.4.1-beta.
