### ISSUE TITLE
JS Errors unreported

### ISSUE THREAD

**Issue by Fordi** [psiho/jsbench-me#12]
Should probably log errors to window.top from the sandbox, because otherwise they're invisible.

**Comment by skeddles** [comment]
ERROR

**Comment by danielocdh** [comment]
error!, error!error!error! error!error!

**Comment by psiho** [comment]
Originally, I designed JSBenchme just for testing. I was writing the code elsewhere and copy/pasting it (at least for longer test) but yes, then started using it as editor too and ran into the same problem.

I'm investigating how to do this now and put in v1 release. Trouble is, Sandbox is pretty locked, only script runs are allowed, not even access-allow-origin so window.top is not accessable from sandbox. All communication is done via PostMessage.

I'll look up how to intercept errors and post them via messsaging system. In that case they could be forwarded to console.

**Comment by psiho** [comment]
This has been fixed for v1 soon to be released. Sandbox errors are now output to console but also visible (shortened to 65 chars) in Case Editor next to "error!" status. HTML Title tag used with full error message so hovering it will display messages longer than 65 chars.
