### ISSUE TITLE
NaN% slower

### ISSUE THREAD

**Issue by baryluk** [psiho/jsbench-me#15]
It appears rather frequently,

```
finished
47,233 ops/s ±1.03%
NaN% slower

finished
2,592,311 ops/s ±8.68%
fastest

finished
2,696,314 ops/s ±8.11%
fastest

finished
382,668 ops/s ±0.49%
NaN% slower

finished
158,730 ops/s ±0.9%
NaN% slower

finished
31,390 ops/s ±0.5%
NaN% slower
``

**Comment by psiho** [comment]
I'll keep this open while finishing up v1 rewrite. I failed to reproduce it during development but I think I have seen it myself running old version long time ago so I'm still not giving up on detecting this.

**Comment by psiho** [comment]
I think I got this. Difficult one to track but I'm quite sure this was related to the fact Benchmark.js can return *multiple* fastest/slowest results (array of test cases). This was handled ok for fastest/slowest detection but one stats number used for the calculation was not expecting array but number. So NaN% would display in the case there were multiple 'fastest' cases. I haven't managed to replicate problem, but I'm pretty positive that's it.  I'm closing it. Will be published with v1.

**Comment by baryluk** [comment]
Sure. When it is published on https://jsbench.me/ I can do further testing.

Thanks.
