### ISSUE TITLE
Negative slower percentage.

### ISSUE THREAD

**Issue by Edgar-P-yan** [psiho/jsbench-me#16]
![image](https://user-images.githubusercontent.com/35116136/51054241-0918af80-15fe-11e9-8fe5-fec7cf614418.png)

**Excepted Result:**
1. Test case №2 marked as fastest as it have 44 ops.

**What We have Got:**
1. Test case №1 marked as fastest, which is the second by ops.
2. Test case №2 without fastets label, but with negative percentage of slowness.

**Comment by psiho** [comment]
Hm, weird. With my simple test on Chrome I don't get this. Can you maybe post link to your test and also say which OS/Browser you use?

**Comment by Edgar-P-yan** [comment]
OS: Windows 10
Browser: Chrome 71
link: <https://jsbench.me/v4jqshw207/1>
Yeah weird. I can't reproduce it again, too. Actually there is one another issue with percentage counting, sometimes it prints NaN%, but I didn't open another issue because there is already opened one. #15

**Comment by Edgar-P-yan** [comment]
OS: Windows 10
Browser: Chrome 71
Link: <https://jsbench.me/v4jqshw207/1>
Yeah weird. Now I cant reproduce it, too. Actually there is one another issue with "slower" calculation. Sometimes it prints NaN%, but I didn't open a new issue, because there is already one opened. #15

**Comment by Edgar-P-yan** [comment]
OS: Windows 10
Browser: Chrome 71
link: <https://jsbench.me/v4jqshw207/1>
Yeah weird. Now I cant reproduce it, too. Actually there is another issue with "slower" calculation. Sometimes it prints NaN%. But I didn't open a new issue because there is one opened. #15

**Comment by psiho** [comment]
During migration to new React and Mobx (v1) I have tried to reproduce this many times with many browsers and always failed. I'll have to close this and hope it goes away for others with v1 too.

**Comment by Edgar-P-yan** [comment]
@psiho yeah, hope it will not affect v1 too :)
