### ISSUE TITLE
Unable to confirm account after leaving page when signing up

### ISSUE THREAD

**Issue by ChrisBrownie55** [psiho/jsbench-me#17]
**Issue:**
 - I signed up for an account on jsbench.me
 - I opened my email to get the code
 - I accidentally left the jsbench.me site and returned
 - I am unable to login, or retry signing up, or enter my verification code to confirm my account

**Comment by psiho** [comment]
I have manually activated your account. Please try to login with credentials you used at signup. If it doesn't work or you forgot those I can try deleting your account so you ca sign up again.

**Comment by ChrisBrownie55** [comment]
@psiho That worked, thank you!

**Comment by blw043** [comment]
I have also encountered this issue. In my case I did not receive the confirmation email even though my email address was correct. I suspect this is my mailserver's fault. However, after refreshing the page I can no longer retry login.

**Comment by psiho** [comment]
@blw043 sorry, very limited time to fix this personally. Do you want me to manually activate you your account or you created a new one already?

**Comment by VinayRajput** [comment]
@psiho, I am also facing same issue as @blw043 faced, please activate my account,

Thanks and regards
Vinay

**Comment by psiho** [comment]
As of v1 that is being worked on, I will completely move away from validatio codes to validation emails with a link to confirm email. This will make UI simpler and the process better. 

p.s. @VinayRajput I've confirmed your acc manually. Sorry for being late but since I started rewrite I stopped monitoring issues closely.

**Comment by psiho** [comment]
I'm closing this as I migrated to Amazon SES for sending out emails and jsbenchme just went out of sanbox mode for SES. Already before, I changed verification from code to email so ther's no need to keep verification part of UI at all.

Just some final build optimizations left before v1 is live so want old issues out of the way.
