### ISSUE TITLE
[Feature Request] A way to reorder the test

### ISSUE THREAD

**Issue by RedSparr0w** [psiho/jsbench-me#19]
It would be great if there was a way to reorder the test that have already been created.

**Comment by psiho** [comment]
drag & drop is now done for v1. Small sidemenu with arrows pops out on hover, enabling you to do some actions like moving case up or down, running single test, etc. On desktop, also drag&drop of cases work. Touch events for mobile that would enable drag&drop there are left for some future versions. Mobile CSS needs some love anyay and mobile is not a priority as I don't see many people using them to write tests, more just to run them.
