### ISSUE TITLE
[Bug] jQuery throws error if it is used in the first test while cache disabled

### ISSUE THREAD

**Issue by RedSparr0w** [psiho/jsbench-me#20]
jQuery functions will throw an error if it is used in the first test(s) while cache is disabled:
[example test
![example test image](https://i.imgur.com/ugFhPq8.png)](https://jsbench.me/ehizltusdj)

**Note** This only happens if I have DevTools open and cache disabled.

**Comment by psiho** [comment]
good catch. I managed to reproduce it and with latest v1 version in development error is visible and is: ReferenceError: $ is not defined. Looking into it.

**Comment by psiho** [comment]
This one is done for v1. Scripts from SetupHTML were being loaded async and when cache was disabled it caused them do be initialized after test has already started. v1 will not start the test before making sure all the scripts from Setup HTML are loaded ok. If there is an error loading any of them, testing will abort and error message will be output to console and also displayed in Setup Html editor.
