### ISSUE TITLE
Max length for `setup` field

### ISSUE THREAD

**Issue by canonic-epicure** [psiho/jsbench-me#24]
Hi,

Great tool, thanks a lot for it!

Couple of issues:
- the max length for the setup field - 2048 chars is not reasonable. I had to switch back to jsperf because of that
- It would be very helpful to add some splitters to be able to resize the `setup` field, to make it larger (or any other way to resize it).

Thanks again!

**Comment by psiho** [comment]
Ah, I'm aware of this. It was actually extended once already. Technically, it would work with much larger inputs. Technology supports it. Data is stored in AWS Dynamo DB and I believe limit there to be 400KB :)

The reason behind this limit is only one: server costs. I'm paying AWS Dynamo DB, Lambda, API Gateway based on usage (i.e  Lambda by 100ms of execution) and larger the testsuite is, everything gets slower and more expensive. Currently I get like 50.000 test runs per month and fighting to stay on Amazon free-tier (with some other projects of mine).

This will probably change as soon as I setup a donation button or try some minumum of monetization like sponsored text ad, just enough to cover server costs which are not large.

**Comment by psiho** [comment]
I optimized AWS a bit to cut down the costs. It gives me some space to increase limits once more. With v1.1 update coming this weekend, SetupJS and SetupHTML limits for saving is doubled from 2048 characters to 4096.

Further increases will depend on effect of this to hosting costs and your needs. So, if you need even more, let me know.

**Comment by psiho** [comment]
v1.1 is out and limits of 4096 are there. I'm closing this for now. If anybody needs more space, let me know.
