### ISSUE TITLE
Does not clear 'fastest' properly

### ISSUE THREAD

**Issue by markus-walther** [psiho/jsbench-me#25]
When you rerun benchmarks after making edits to one, you might easily get the opposite test to win.

Assuming the UI wants to indicate the current winner after each run, it should never show more than one 'fastest' label, and update it rationally after each run.

Currently the UI ends up showing both tests as 'fastest' in the above scenarios.

**Comment by psiho** [comment]
good catch. I missed it because Benchamrk.js can return more than one case with 'fastest' status, but indeed, speed status was not cleared between running tests. This is fixed now in soon to publish v1.
