### ISSUE TITLE
Multiple <script> tags

### ISSUE THREAD

**Issue by RobbinBaauw** [psiho/jsbench-me#33]
When using multiple `<script>` tags, I get the following error: "error! Cannot find script parent node".

When looking through the sources, I see the following code:
```ts
		for (let i = 0; i < s.length ; i++) {
			const promise: Promise<void> = loadScript(s[i].src)
				.then(() => {
					const parent = s[i].parentElement
					if (!parent) return Promise.reject('error! Cannot find script parent node')
					parent.removeChild(s[i]) //remove script node from setupHtmlPlaceholder div
				})
			promisesBatch.push(promise)
		}
```
When the first item is loaded, `parent.removeChild` is called, so after this iteration the `s` array is of size one. On the next script, `s[i]` will be undefined, as `i = 1`.

**Comment by psiho** [comment]
Thank you for pointing this one out. I was testing with only one script tag :)
I'll try to fix this tonight

**Comment by RobbinBaauw** [comment]
Thanks! Another side-effect of this is the fact that it will be stuck at "running". The button to stop doesn't work, so you'll have to refresh and you've lost your unsaved changes.

**Comment by psiho** [comment]
This is finally fixed and published. Took me some time because of other obligations on paid projects. It was not just a script tag issue but also an issue with improper aborting on sandbox error. The test would hang in "running..." status.
