### ISSUE TITLE
Cannot save because "Validation Errors" cryptic message

### ISSUE THREAD

**Issue by JonDum** [psiho/jsbench-me#4]
Can't save a test ever because all I get is a "validation issue" when trying to save. 

Here's the preparation code I'm trying to save:

```


var _keys = ['foo', 'bar', 'baz', 'bo', 'boom'];
var _valueMax = 20;

// a large array of items with a set amount of keys, with each item having a random number of keys each with its own random value.
var _items = [...new Array(15000)].map(_ => {
  let ret = {}, numKeys = ~~(Math.random()*_keys.length);
  while(numKeys--)
     ret[_keys[~~(Math.random()*_keys.length)]] = ~~(Math.random()*_valueMax)
  return ret;
})
var _filters = [...new Array(1000)].map(_ => {
  return {k: _keys[~~(Math.random()*_keys.length)], v: ~~(Math.random()*_valueMax)}
});

function applyFilters(items, exclusions) {
  exclusions.forEach(exclusion => {
    items = items.filter( item => item[exclusion.k] !== exclusion.v )
  });
  return items;
}

var regexFilters = { }
for(var i = 0; i < _filters.length; i++) {
  var filter = _filters[i];
  if(regexFilters[filter.k])
    regexFilters[filter.k].push(filter.v)
  else
    regexFilters[filter.k] = [filter.v]
}
for(var key in regexFilters) {
  regexFilters[key] = new RegExp(regexFilters[key].join('|'));
}

function applyFiltersRegex(items, exclusions) {
  return items.filter( item => {
    for(var key in regexFilters) {
      if(item[key] && regexFilters[key].test(item[key]))
         return false;
    }
    return true;
  });
}

```

Perfectly valid code. Maybe just turn off the save requiring validation?

**Comment by psiho** [comment]
I think the problem is that I limited source code to 1000 characters in database so it got truncated. I'll increase the limit and also add validation for it in Suite editor so it is not confusing when/if it happens.

Thank you for your input!

**Comment by JonDum** [comment]
Nice! Welcome back :)

**Comment by 0x1c97d5f** [comment]
issue: my setup code for four tests is 2265 characters (and i was thinking i'd add more)

i tried putting each test's setup code inside the test itself but the results are different (must get optimized differently)

**Comment by psiho** [comment]
Hm, I have to setup limit somewhere. Jsbenchme is a serverless app, using AWS Lambda, AWS API Gateway, AWS DynamoDB and AWS Cognito... all withing free tier. That's what makes Jsbenchme free and with no ads. Adding indexes to DynamoDB, increasing payload, etc. brings it to the limits of free tier which would force me to add ads, some commercial services or search for hosting sponsors.

I'll have to think about this and analyse my spending once more. Then maybe increase limits to 4KB from current 2KB.

In the meantime, can you please copy/paste your test here so maybe we can find some workaround?
