### ISSUE TITLE
Color text of 'text suite description' must be changed when in dark mode

### ISSUE THREAD

**Issue by CARSsimoes** [psiho/jsbench-me#40]
Color text of  'text suite description' remains black in dark mode. It is very difficult to know what user has already write

![error1](https://user-images.githubusercontent.com/37809297/106885774-fe488000-66da-11eb-8b18-4f135a24bfcc.png)

**Comment by psiho** [comment]
Thx for noticing, This has been fix in latest update but still not published. Will be when v1.1 goes out.
