### ISSUE TITLE
When trying to login, I receive the "User is not confirmed." error

### ISSUE THREAD

**Issue by trezy** [psiho/jsbench-me#45]
I've created an account before, but I never received the confirmation email. Now when I try to login, I get an error that my user account hasn't been confirmed. It would seem there's no way to resend the confirmation email, so I'm stuck.

!["User not confirmed" error](https://user-images.githubusercontent.com/442980/126549961-0bb45556-df7b-4639-be64-2c0586e0c644.png)

**Comment by psiho** [comment]
Oh yes, completely forgot huge parts of AWS Cognito implementation in v1 :)

Try to login now.

**Comment by trezy** [comment]
It works like a dream now! Thanks! 🤗

**Comment by CWSpear** [comment]
I'm getting this error, too. Similar situation to @trezy. I had an account previously, but I can't sign in, can't reset my password, can't create an account (with the same username)...

When I try to log in with my account, I get that **User is not confirmed** error

**Comment by psiho** [comment]
@CWSpear , try again

**Comment by CWSpear** [comment]
It worked, thank you @psiho

**Comment by Autumnlight02** [comment]
I have the same issue as the other two here
