### ISSUE TITLE
Why custom functions are undefined with DEFER

### ISSUE THREAD

**Issue by cyfung1031** [psiho/jsbench-me#46]
https://jsbench.me/dekrew1ytu/1

With defer, only external script can work. I don't understand why.
How to make my custom functions work with DEFER??

![acsdcd](https://user-images.githubusercontent.com/44498510/126639305-f88bd1ea-29eb-4292-b00d-1206eba7466a.png)

**Comment by psiho** [comment]
SetupHTML script will not work (for now). Script tag there is disabled but I'm probably going to enable it in the next release. See #36 

As for correct way to do it, in Setup JavaScript, I think it is related to JavaScript scope. So try using var instead of let.

**Comment by cyfung1031** [comment]
> SetupHTML script will not work (for now). Script tag there is disabled but I'm probably going to enable it in the next release. See #36

**SetupHTML** - begining of all tests
**SetupJS** - begining of each test
so there is no JS at the begining of all tests

> As for correct way to do it, in Setup JavaScript, I think it is related to JavaScript scope. So try using var instead of let.

Great! Problem solved. Thank you.

I have also tried other ways to do that but in vain.
`const` and `let` are not working.
`window.func1 = ....` and `document.func1 = ...` are also not working

**Comment by psiho** [comment]
> **SetupHTML** - begining of all tests
> **SetupJS** - begining of each test
> so there is no JS at the begining of all tests

I don't see a need for "run at the beginning of all tests". SetupJS runs at the beginning of each test loop. SetupHTML, as the name suggests, sets up HTML mostly used when you want to test DOM manipulation.
But to cut long story short, this is not JSBench.me's idea. It's Benchmark.js on which it is based. JSBench.me is just a frontend to it. And to learn more about setting up benchmarks in benchmark.js I suggest going through their docs.
