### ISSUE TITLE
Feature: User profile page

### ISSUE THREAD

**Issue by joseluisq** [psiho/jsbench-me#5]
It would be great if you could provide a profile page (`https://jsbench.me/username`) for view the history of the benchmarks created by user.

**Comment by psiho** [comment]
Thank you for your input. Yes, I see how that could be useful, nut just on the public side but also for users themselves lik "my benchmarks". I guess some minimal benchmark management should be added too, to delete items from the list and possible multi-item delete too to clean up after some time. 

I'll put it on my feature list.

**Comment by joseluisq** [comment]
> I'll put it on my feature list.

Awesome! 👍

**Comment by psiho** [comment]
v0.3.6-beta is out and basic user profile page is added there. You can find it in user menu in top-right corner. It's also accessible publicly through jsbench.me/user/<username>

For now, I'm closing this issue, and will think about benchmarks management (batch-delete and similar) after we see what exactly is needed.
