### ISSUE TITLE
Format ops/s numbers

### ISSUE THREAD

**Issue by slightlyfaulty** [psiho/jsbench-me#50]
I think it would be really nice if the result **ops/s** numbers were formatted with thousand separators, to make them easier to read when benchmarking very fast operations and the ops/s are in the millions.

For example `222222222.22 ops/s` vs `222,222,222.22 ops/s` you can quickly see that it's ~222 million without needing to count the numbers carefully. The cognitive load really adds up if you do a lot of benchmarking.

Thank you for creating and maintaining jsbench.me. It is by far the best JS benchmarking site on the internet and is a great asset to the community ❤️

**Comment by psiho** [comment]
Thx. It's on the list. Now I just need to find time and release an update with issues like this resolved

**Comment by rik** [comment]
Nowadays, the functionality is built-in with [`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat). You could even use the preferred formatting of the visitor.

**Comment by psiho** [comment]
I went with `Intl.NumberFormat(undefined, {notation: 'compact'}).format(value)` which creates short representation of the number in locale of the browser. In example:

```
0.000123445 = 0.00012
0.12345 = 0.12
1.2345 = 1.2
123.4567 = 123
123456.789123 = 123K
123456789.123456 = 123M
123456789123.12346 = 123B
```
will be a part of v1.2 release.
