### ISSUE TITLE
support top level await

### ISSUE THREAD

**Issue by NullVoxPopuli** [psiho/jsbench-me#52]
this is reproducible with a test case of:
```
await Promise.resolve();
```

**Comment by douglasg14b** [comment]
Seriously need this.

How can we run setup code for the tests if we need to load something from a URL?

BY the time the promises are resolved the tests are already running, and we can't block it with await...

**Comment by psiho** [comment]
It's been long time, but it would help if you elaborate a bit what you're trying to achieve here. For async tests, "defer" checkbox is used. For async SetupJS, I'm not sure what the use case would be. Also, please note that all tests and setup code is run in a sandbox, so no external world exists for it, and no external URLs can be accessed from it. I don't want this tool to be used to attack or spam external domains from jsbench.me domain.

**Comment by psiho** [comment]
Also.... JSBench.me is just a frontend to Benchmark.js, so you can also ask there about testing procedures. Authors of Benchmark.js are much more knowledgable about that topic. My guess is that this question is what you want: https://github.com/bestiejs/benchmark.js/issues/36

... but still, would like to know what exactly you're trying to achieve. My guess is that you're doing something wrong, and that current benchmark.js functionality can cover your use case.

**Comment by NullVoxPopuli** [comment]
How do you benchmark async functions with jsbench?

**Comment by psiho** [comment]
use a 'deferred' checkbox for async funcs you're testing. then deferred.resolve() at the end of it.

similar question: https://stackoverflow.com/questions/31624055/benchmark-asynchronous-code-benchmark-js-node-js
