### ISSUE TITLE
[Feature] Common JS to run once before test suite

### ISSUE THREAD

**Issue by lukasradek** [psiho/jsbench-me#53]
Just like we have a JS setup to run before each test, it would be great to have a JS "pre-setup", that would run once per whole test.
For example for generating random sequences for testing, which would then stay the same for all tests.

**Comment by m-paternostro** [comment]
This would be indeed a great feature. Besides the random sequences, it would also allow for defining constants for all tests. This is particular important when benchmarking code that use regex because we can precompile them as we would on a real application.

**Comment by lukasradek** [comment]
Well.... quite some time passed between now and my request but I think that "what @m-paternostro mentioned is exactly what I meant". I simply needed to generate random sequence for the whole test because otherwise it is not much of a test if different dataset is generated for each test case / cycle. So from my standpoint it is insignificant whether SetupJS runs before each test or cycle. I need javascript to run once per the whole test suite.
