### ISSUE TITLE
Digit grouping in ops/sec display

### ISSUE THREAD

**Issue by SimonLundberg** [psiho/jsbench-me#56]
Sometimes you get a *lot* of ops/sec, and comparing them between separate browsers at a glance would be easier if there was digit grouping in the display. See following screenshots for a comparison of current / proposed.

<img width="244" alt="Screenshot 2022-04-01 at 15 03 22" src="https://user-images.githubusercontent.com/20053041/161269149-041ddebd-f285-434a-aa7e-7ae86757f62d.png">
<img width="276" alt="Screenshot 2022-04-01 at 15 03 57" src="https://user-images.githubusercontent.com/20053041/161269143-59c04239-b4f9-47df-b6ee-1d9c8babe26e.png">

**Comment by psiho** [comment]
This is related to #50 and I think solution there covers it too.
