### ISSUE TITLE
Confirmation email not received

### ISSUE THREAD

**Issue by daiplusplus** [psiho/jsbench-me#58]
I tried to sign-up just now, but I never received the confirmation email (assuming you have access to your own users-database, look for a signup around 2022-07-09 09:29 UTC (so ~3 minutes ago) with an e-mail address ending in `.me`.)

If it helps, I use Office 365. There's nothing in my inbox nor junk folder.

**Comment by psiho** [comment]
Sorry, but I missed this issue somehow. Hopefully, we get rid of this registration process and implement GitHub/Google login in v1.2 release.

If you still need help with this, let me know.

**Comment by daiplusplus** [comment]
@psiho I'm currently blocked from logging in: there doesn't seem to be a way to re-send the confirmation email.

![image](https://user-images.githubusercontent.com/1693078/231808105-365888e5-0f54-471a-aa50-d4dd03e5cd8c.png)

and I can't re-register because my username is already in-use:

![image](https://user-images.githubusercontent.com/1693078/231808542-f3673d0f-cc98-4769-a0d3-7c7bd56f01d1.png)

**Comment by psiho** [comment]
Yes, this is a flow in signing process. For now, I deleted your username so you can retry. Check spam folder, maybe mail is there. If the same problem arises, let me know and I'll confirm it manually.

I wanted to update this in v1.2, but after finding out AWS Cognito does not support Github login, I decided to drop it altogether and change Auth providers. So I didn't want to spend more time fixing this with AWS Cognito. Next version will have updated authentication.

**Comment by daiplusplus** [comment]
I tried again and registration succeeded, but I still haven't received the welcome/confirmation email so I still can't login.

Nothing in my junk folder and Office 365 isn't saying it's dropped any incoming emails either.

**Comment by psiho** [comment]
Try now to login. I manually enabled it.
Amazon Cognito sends out emails from their own server. Difficult to track where those are stuck.

**Comment by daiplusplus** [comment]
> Try now to login. I manually enabled it.

Thanks - I'm logged-in now.

Does it matter that I'm using Gmail-style disposable addressess, like `foo+websitename@domainname.com` ? Just a thought....

**Comment by psiho** [comment]
tbh, I don't know. Very few people had the same issue before and they didn't use that format, so I don't think so. But there is a ton of factors mail servers use to decide what mail is suspicious and block it. Both on Amazon outgoing side or your mail server incoming side.
