### ISSUE TITLE
mixed content errors

### ISSUE THREAD

**Issue by echopoint** [psiho/jsbench-me#6]
Minor issue on the page, but getting mixed content errors in firefox and in chrome there are more.

![chrome-mxed-content-screenshot jpg](https://user-images.githubusercontent.com/32996843/32631394-07c48378-c598-11e7-8b6c-435c5575d63b.jpg)

![mixed-content-screenshot1 jpg](https://user-images.githubusercontent.com/32996843/32631309-b75bd1f2-c597-11e7-9ba6-82a58b8c5df5.jpg)

**Comment by psiho** [comment]
Thank you for noticing this. It seems few fonts were linked via HTTP instead of HTTPS. It is fixed now and v0.3.7 is published. Please refresh your browser before testing to be sure latest version is loaded.

**Comment by echopoint** [comment]
Yeah, that's good now..
