### ISSUE TITLE
Operators have background in dark theme but not light theme

### ISSUE THREAD

**Issue by amitbeck** [psiho/jsbench-me#60]
Dark theme:
![image](https://user-images.githubusercontent.com/22454058/188856813-7c7ef6a3-4877-4a90-9ace-13a5da45cbb8.png)

Light theme:
![image](https://user-images.githubusercontent.com/22454058/188856945-5d3a5b9e-cae4-4f72-87bb-2dc5a68733a5.png)

The background makes the code harder to read (and IMO pretty ugly).
Please consider removing the `background` property from `.language-css .token.operator` in the CSS.

**Comment by psiho** [comment]
done. will be published with v1.2 reelase.
