### ISSUE TITLE
Malware pop-ups

### ISSUE THREAD

**Issue by jaredkrinke** [psiho/jsbench-me#61]
I consistently get a malware pop-up on this link: http://jsben.ch/lO6C5

**Comment by psiho** [comment]
I believe you poated to the weong project page. This is jsbench.me and not jsben.ch

But interesting to see. I guess it payed off to really dive into sandbox modes, blocking scripts and external sites because so far I have never got a report like this for jsbench.me

**Comment by jaredkrinke** [comment]
Oops. Sorry about that! I'll try and find the right project.
