### ISSUE TITLE
Is Jsbench down?

### ISSUE THREAD

**Issue by Autumnlight02** [psiho/jsbench-me#63]
![image](https://user-images.githubusercontent.com/68244453/218314567-e0bd5525-6a85-4870-9067-c5b2660ac26b.png)
And if so would it be possible to get my benchmarks out?

**Comment by psiho** [comment]
Wow... it was set to autorenew. Don't know what happened but I'll deal with it right away

**Comment by psiho** [comment]
I think I need to change DNS provider... thay haven't really tried anything after the card bounced! Thanks for letting me know. It should be back online any minute now.

**Comment by Autumnlight02** [comment]
:3 I tried to buy it asap bec i was afriad someone steals it, but looks like all went well

**Comment by Autumnlight02** [comment]
Thank you for your service sir!

**Comment by psiho** [comment]
Thank you  for letting me know. DOn't worry, Jsbench.me is not going anywhere :) New development might be slow but will not go offline. BTW, feature to export/import all benchmarks (and run it on local instance) is on top of my list. I just wish a day had 48 hours :)

**Comment by Autumnlight02** [comment]
@psiho I would be interested in helping you a bit

**Comment by psiho** [comment]
I was very close to that, rewrote the whole thing to make it more maintanable and make the code public... but Covid stuff just turned my life upside down and I'm still not back to "normal". Another rewrite is well overdue but let's hope that one becomes public and then I let people in to make changes, fork, etc.
