### ISSUE TITLE
test not working https://jsbench.me/nuk5skh6qi/1

### ISSUE THREAD

**Issue by mtraining-2022** [psiho/jsbench-me#65]
test not working https://jsbench.me/nuk5skh6qi/1
after pressing the button run, the colored bar spins and the test freezes

but if this test is typed separately manually without writing the test to the site (update), then it works

**Comment by psiho** [comment]
Thank you for reporting this. It is a CORS issue that somehow  passed my testing before last update. I'm on it.

**Comment by psiho** [comment]
In the meantime, just remove version from the url, bug is in versioning. So, use https://jsbench.me/nuk5skh6qi

**Comment by psiho** [comment]
This is done and published to v1.2.2
