### ISSUE TITLE
stuck on "pending..." in edge 

### ISSUE THREAD

**Issue by KaelWD** [psiho/jsbench-me#8]
Clicking "abort" then throws `SCRIPT438: Object doesn't support property or method 'abort'` to the console

EdgeHTML 16.16299 on Windows 10 build 16299.98
URL: https://jsbench.me/7ejagsewtr

**Comment by psiho** [comment]
Finally support for MS browsers is added. I tested on Edge 40 and IE 11. It was not about polyfills only (but I added them too) but in a funny way IE deals with postMessage and sandboxed iframes.

I'd like to see reports of other, older, MS browsers.
